package com.fpoly.thainv.entities;
// Generated Jun 6, 2024, 12:44:43 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Attributes generated by hbm2java
 */
@Entity
@Table(name = "attributes", schema = "dbo", catalog = "TMDT")
public class Attributes implements java.io.Serializable {

	private Integer attributeId;
	private String attributeKey;
	private String value;
	private Set<AttributeProduct> attributeProducts = new HashSet<AttributeProduct>(0);

	public Attributes() {
	}

	public Attributes(String attributeKey, String value) {
		this.attributeKey = attributeKey;
		this.value = value;
	}

	public Attributes(String attributeKey, String value, Set<AttributeProduct> attributeProducts) {
		this.attributeKey = attributeKey;
		this.value = value;
		this.attributeProducts = attributeProducts;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "attribute_id", unique = true, nullable = false)
	public Integer getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(Integer attributeId) {
		this.attributeId = attributeId;
	}

	@Column(name = "attribute_key", nullable = false, length = 100)
	public String getAttributeKey() {
		return this.attributeKey;
	}

	public void setAttributeKey(String attributeKey) {
		this.attributeKey = attributeKey;
	}

	@Column(name = "value", nullable = false, length = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attributes")
	public Set<AttributeProduct> getAttributeProducts() {
		return this.attributeProducts;
	}

	public void setAttributeProducts(Set<AttributeProduct> attributeProducts) {
		this.attributeProducts = attributeProducts;
	}

}
