package com.fpoly.thainv.entities;
// Generated Jun 6, 2024, 12:44:43 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Manufacturers generated by hbm2java
 */
@Entity
@Table(name = "manufacturers", schema = "dbo", catalog = "TMDT")
public class Manufacturers implements java.io.Serializable {

	private Integer manufacturerId;
	private String manufacturerName;
	private String country;
	private Set<Products> productses = new HashSet<Products>(0);

	public Manufacturers() {
	}

	public Manufacturers(String manufacturerName) {
		this.manufacturerName = manufacturerName;
	}

	public Manufacturers(String manufacturerName, String country, Set<Products> productses) {
		this.manufacturerName = manufacturerName;
		this.country = country;
		this.productses = productses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "manufacturer_id", unique = true, nullable = false)
	public Integer getManufacturerId() {
		return this.manufacturerId;
	}

	public void setManufacturerId(Integer manufacturerId) {
		this.manufacturerId = manufacturerId;
	}

	@Column(name = "manufacturer_name", nullable = false, length = 100)
	public String getManufacturerName() {
		return this.manufacturerName;
	}

	public void setManufacturerName(String manufacturerName) {
		this.manufacturerName = manufacturerName;
	}

	@Column(name = "country", length = 100)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "manufacturers")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
