package com.fpoly.thainv.entities;
// Generated Jun 6, 2024, 12:44:43 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * OrderStatus generated by hbm2java
 */
@Entity
@Table(name = "order_status", schema = "dbo", catalog = "TMDT")
public class OrderStatus implements java.io.Serializable {

	private Integer statusId;
	private String statusName;
	private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<PurchaseOrders> purchaseOrderses = new HashSet<PurchaseOrders>(0);

	public OrderStatus() {
	}

	public OrderStatus(String statusName) {
		this.statusName = statusName;
	}

	public OrderStatus(String statusName, Set<Orders> orderses, Set<PurchaseOrders> purchaseOrderses) {
		this.statusName = statusName;
		this.orderses = orderses;
		this.purchaseOrderses = purchaseOrderses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "status_id", unique = true, nullable = false)
	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	@Column(name = "status_name", nullable = false, length = 50)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderStatus")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderStatus")
	public Set<PurchaseOrders> getPurchaseOrderses() {
		return this.purchaseOrderses;
	}

	public void setPurchaseOrderses(Set<PurchaseOrders> purchaseOrderses) {
		this.purchaseOrderses = purchaseOrderses;
	}

}
