package com.fpoly.thainv.entities;
// Generated Jun 6, 2024, 12:44:43 AM by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * PurchaseOrderDetails generated by hbm2java
 */
@Entity
@Table(name = "purchase_order_details", schema = "dbo", catalog = "TMDT")
public class PurchaseOrderDetails implements java.io.Serializable {

	private Integer purchaseOrderDetailId;
	private Products products;
	private PurchaseOrders purchaseOrders;
	private int quantityOrdered;
	private BigDecimal unitPrice;

	public PurchaseOrderDetails() {
	}

	public PurchaseOrderDetails(int quantityOrdered, BigDecimal unitPrice) {
		this.quantityOrdered = quantityOrdered;
		this.unitPrice = unitPrice;
	}

	public PurchaseOrderDetails(Products products, PurchaseOrders purchaseOrders, int quantityOrdered,
			BigDecimal unitPrice) {
		this.products = products;
		this.purchaseOrders = purchaseOrders;
		this.quantityOrdered = quantityOrdered;
		this.unitPrice = unitPrice;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "purchase_order_detail_id", unique = true, nullable = false)
	public Integer getPurchaseOrderDetailId() {
		return this.purchaseOrderDetailId;
	}

	public void setPurchaseOrderDetailId(Integer purchaseOrderDetailId) {
		this.purchaseOrderDetailId = purchaseOrderDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "purchase_order_id")
	public PurchaseOrders getPurchaseOrders() {
		return this.purchaseOrders;
	}

	public void setPurchaseOrders(PurchaseOrders purchaseOrders) {
		this.purchaseOrders = purchaseOrders;
	}

	@Column(name = "quantity_ordered", nullable = false)
	public int getQuantityOrdered() {
		return this.quantityOrdered;
	}

	public void setQuantityOrdered(int quantityOrdered) {
		this.quantityOrdered = quantityOrdered;
	}

	@Column(name = "unit_price", nullable = false, precision = 10)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

}
