package com.fpoly.thainv.entities;
// Generated Jun 6, 2024, 12:44:43 AM by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

/**
 * Statistic generated by hbm2java
 */
@Entity
@Table(name = "statistic", schema = "dbo", catalog = "TMDT")
public class Statistic implements java.io.Serializable {

	private Integer statisticId;
	private Date timestamp;
	private BigDecimal sales;
	private int websiteTraffic;
	private String otherMetrics;

	public Statistic() {
	}

	public Statistic(BigDecimal sales, int websiteTraffic) {
		this.sales = sales;
		this.websiteTraffic = websiteTraffic;
	}

	public Statistic(BigDecimal sales, int websiteTraffic, String otherMetrics) {
		this.sales = sales;
		this.websiteTraffic = websiteTraffic;
		this.otherMetrics = otherMetrics;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "statistic_id", unique = true, nullable = false)
	public Integer getStatisticId() {
		return this.statisticId;
	}

	public void setStatisticId(Integer statisticId) {
		this.statisticId = statisticId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "sales", nullable = false, precision = 10)
	public BigDecimal getSales() {
		return this.sales;
	}

	public void setSales(BigDecimal sales) {
		this.sales = sales;
	}

	@Column(name = "website_traffic", nullable = false)
	public int getWebsiteTraffic() {
		return this.websiteTraffic;
	}

	public void setWebsiteTraffic(int websiteTraffic) {
		this.websiteTraffic = websiteTraffic;
	}

	@Column(name = "other_metrics")
	public String getOtherMetrics() {
		return this.otherMetrics;
	}

	public void setOtherMetrics(String otherMetrics) {
		this.otherMetrics = otherMetrics;
	}

}
